// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lawbnbawxvbhsemmjdku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxhd2JuYmF3eHZiaHNlbW1qZGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjU2NjksImV4cCI6MjA2ODQ0MTY2OX0.eLXM7hH9MrkBx9s6ai7-Rki_0TfLdkMJqYwVNbUY2GA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});